#!/usr/bin/env bash
#Script that fix the Nginx configuration file to listen to port 80
sudo service nginx stop
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart
