#!/usr/bin/env bash
# This script is displaying information about the school file

filename="school"
if [ ! -e $filename ]
then
	echo "school file does not exist"
	exit 0
fi

echo "school file exists"

if [ -s $filename ]
then
	echo "school file is not empty"
else
	echo "school file is empty"
fi

if [ ! -d $filename ]
then
	echo "school is a regular file"
fi
